main : com.clashwars.cwevents.CWEvents
name: ${project.artifactId}
version: ${project.version}
description: ${project.description}
depend: [CWCore]
commands:
  event:
    description: Main event command
    usage: /<command>
    aliases: [events, e]
  loc:
    description: Location management
    usage: /<command>
  leave:
    description: Leave the events server.
    usage: /<command>
    aliases: [quit, pvp]