main : com.clashwars.cwevents.CWEvents
name: ${project.artifactId}
version: ${project.version}
description: ${project.description}
commands:
  event:
    description: Main event command
    usage: /<command>
  loc:
    description: Location management
    usage: /<command>